<?php

$colposcopias = $colposcopia->result()[0];
$pdf=new FPDF();
$pdf->addpage();
$pdf->Image('public/img/theme/logo.png' , 10 ,9, 25 , 20,'png');
$pdf->Image('public/colposcopia/'.$colposcopias->imagen1 , 35 ,115, 60 , 40,'JPG');
$pdf->Image('public/colposcopia/'.$colposcopias->imagen2 , 120 ,115, 60 , 40,'JPG');
$pdf->SetFont('Times','',13);
$pdf->Ln(1);
$pdf->Cell(65,6,'', '', 0,'L', false );
$pdf->Cell(60,6,'Centro Medico Especializado', '', 0,'L', false );
$pdf->Ln(5);
$pdf->Cell(72,6,'', '', 0,'L', false );
$pdf->Cell(1,6,'Salud Madre & Mujer', '', 0,'L', false );
$pdf->Ln(5);
$pdf->Cell(60,6,'', '', 0,'L', false );
$pdf->Cell(7,6,'Av Salaverry 1402 - Urb. Bancarios', '', 0,'L', false );
$pdf->Ln(2);
$pdf->Cell(42,5,'', '', 0,'L', false );
$pdf->Cell(60,5,'_____________________________________________', '', 0,'L', false );
$pdf->SetFont('Times','b',13);
$pdf->Ln(10);
$pdf->Cell(62,6,'', '', 0,'L', false );
$pdf->Cell(60,6,'INFORME DE COLPOSCOPIA', '', 0,'L', false );
$pdf->SetFont('Times','B',9);
$pdf->Ln(14);
$pdf->Cell(80,6,'NOMBRE DEL PACIENTE', 1, 0,'C', false );
$pdf->Cell(70,6,'NRO. DE DOCUMENTO', 1, 0,'C', false );
$pdf->Cell(40,6,'FECHA', 1, 0,'C', false );
$pdf->SetFont('Times','',9);
$pdf->Ln(6);
$pdf->Cell(80,6,$colposcopias->apellido." ".$colposcopias->nombre, 1, 0,'C', false );
$pdf->Cell(70,6,$colposcopias->paciente, 1, 0,'C', false );
$pdf->Cell(40,6,date("d-m-Y", strtotime($colposcopias->fecha)), 1, 0,'C', false );
$pdf->SetFont('Arial', '', 11);
$pdf->Ln(9);
$pdf->Cell(1,6,'', '', 0,'L', false );
$pdf->Cell(70,6,'Detalle del Informe', '', 0,'L', false );
$pdf->SetFont('Times','B',9);
$pdf->Ln(8);
$pdf->Cell(50,6,'U.Escamo Columnar', 1, 0,'C', false );
$pdf->Cell(50,6,'Endo Cervix', 1, 0,'C', false );
$pdf->Cell(45,6,'Vagina', 1, 0,'C', false );
$pdf->Cell(45,6,'Vulva', 1, 0,'C', false );
$pdf->SetFont('Times','',9);
$pdf->Ln(6);
$pdf->Cell(50,6,$colposcopias->escamo_columnar, 1, 0,'C', false );
$pdf->Cell(50,6,$colposcopias->endo_cervix, 1, 0,'C', false );
$pdf->Cell(45,6,$colposcopias->vagina, 1, 0,'C', false );
$pdf->Cell(45,6,$colposcopias->vulva, 1, 0,'C', false );
$pdf->SetFont('Times','B',9);

$pdf->Ln(11);
$pdf->Cell(50,6,'Perineo', 1, 0,'C', false );
$pdf->Cell(50,6,'Region parianal', 1, 0,'C', false );
$pdf->Cell(45,6,'Biopsia', 1, 0,'C', false );
$pdf->Cell(45,6,'Papanicolaou', 1, 0,'C', false );
$pdf->SetFont('Times','',9);
$pdf->Ln(6);
$pdf->Cell(50,6,$colposcopias->perineo, 1, 0,'C', false );
$pdf->Cell(50,6,$colposcopias->region_Parianal, 1, 0,'C', false );
$pdf->Cell(45,6,$colposcopias->biopsia, 1, 0,'C', false );
$pdf->Cell(45,6,$colposcopias->papanicolaou, 1, 0,'C', false );
$pdf->SetFont('Times','B',10);
$pdf->Ln(80);
$pdf->Cell(1,6,'', '', 0,'L', false );
$pdf->Cell(70,6,'CONCLUSIONES', '', 0,'L', false );
$pdf->SetFont('Times','',10);
$pdf->Ln(7);
$pdf->SetFont('Arial', '', 10);
$pdf->MultiCell(190, 5,$colposcopias->conclusiones, '', 'L', false);
$pdf->Ln(60);
$pdf->Cell(73,6,'', '', 0,'L', false );
$pdf->Cell(70,6,$colposcopias->medico, '', 0,'L', false );
$pdf->Ln(6);
$pdf->Cell(78,6,'', '', 0,'L', false );
$pdf->Cell(70,6,'CPM'. $colposcopias->cmp, '', 0,'L', false );

$pdf->Output();

?>
