<?php

$generales = $general->result()[0];
// print_r($generales);

$pdf=new FPDF();
$pdf->addpage();
$pdf->Image('public/img/theme/logo.png' , 10 ,9, 25 , 20,'png');

$pdf->SetFont('Times','',13);
$pdf->Ln(1);
$pdf->Cell(40,6,'', '', 0,'L', false );
$pdf->Cell(60,6,'CENTRO ESPECIALIZADO SALUD MADRE & MUJER', '', 0,'L', false );
$pdf->Ln(8);
$pdf->Cell(50,6,'', '', 0,'L', false );
$pdf->Cell(1,6,'HISTORIA CLINICA MEDICINA GENERAL', '', 0,'L', false );
$pdf->SetFont('Times','B',9);
$pdf->Ln(12);
$pdf->Cell(35,6,'1. ANEMISIS', '', 0,'L', false );
$pdf->SetFont('Times','',9);
$pdf->Ln(6);
$pdf->Cell(50,6,'TIPO DE ANEMISIS', '', 0,'L', false );
$pdf->Cell(35,6,'DIRECTA (   )', '', 0,'L', false );
$pdf->Cell(45,6,'INDIRECTA (    )', '', 0,'L', false );
$pdf->Cell(1,6,'MIXTA (    )', '', 0,'L', false );
$pdf->Ln(6);
$pdf->Cell(15,6,'FECHA:', '', 0,'L', false );
$pdf->Cell(115,6,$generales->fecha, '', 0,'L', false );
$pdf->Cell(15,6,'HORA:', '', 0,'L', false );
$pdf->Cell(20,6,$generales->hora, '', 0,'L', false );
$pdf->Ln(5);
$pdf->Cell(40,6,'APELLIDOS Y NOMBRES:', '', 0,'L', false );
$pdf->Cell(120,6,$generales->apellido." ".$generales->pacientes, '', 0,'L', false);

$pdf->Ln(5);
$pdf->Cell(15,6,'EDAD:', '', 0,'L', false );
$pdf->Cell(115,6,$generales->edad, '', 0,'L', false);
$pdf->Cell(15,6,'SEXO:', '', 0,'L', false );
$pdf->Cell(120,6,$generales->sexo, '', 0,'L', false);
$pdf->SetFont('Times','',9);
$pdf->Ln(6);
$pdf->Cell(50,6,'ASEGURADO (   )', '', 0,'L', false );
$pdf->Cell(35,6,'EMPRESA ', '', 0,'L', false );
$pdf->Cell(45,6,'COMPANIA', '', 0,'L', false );
$pdf->Cell(1,6,'IAFA', '', 0,'L', false );
$pdf->Ln(6);
$pdf->Cell(50,6,'', '', 0,'L', false );
$pdf->Cell(35,6,$generales->empresa, '', 0,'L', false );
$pdf->Cell(45,6,$generales->compania, '', 0,'L', false );
$pdf->Cell(1,6,$generales->iafa, '', 0,'L', false );
$pdf->Ln(6);
$pdf->Cell(70,6,'NOMBRE Y APELLIDOS DEL ACOMPANATE:', '', 0,'L', false );
$pdf->Cell(120,6,$generales->nombre_acompanante, '', 0,'L', false);
$pdf->Ln(6);
$pdf->Cell(10,6,'DNI:', '', 0,'L', false );
$pdf->Cell(70,6,$generales->dni, '', 0,'L', false);
$pdf->Cell(20,6,'CELULAR:', '', 0,'L', false );
$pdf->Cell(120,6,$generales->celular, '', 0,'L', false);

$pdf->Cell(20,6,'2', '', 0,'L', false );
$pdf->SetFont('Times','B',9);
$pdf->Ln(7);
$pdf->Cell(27,6,'2. MOTIVO CONSULTA', '', 0,'L', false );
$pdf->SetFont('Times','',9);
$pdf->Ln(5);
$pdf->MultiCell(160, 5,$generales->motivo_consulta, '', 'L', false);
$pdf->Ln(1);
$pdf->Cell(45,6,'ENFERMEDAD ACTUAL:', '', 0,'L', false );
$pdf->Cell(120,6,$generales->enfermedad_actual, '', 0,'L', false);
$pdf->Ln(6);
$pdf->Cell(45,6,'TIEMPO DE ENFERMEDAD', '', 0,'L', false );
$pdf->Cell(25,6,$generales->tiempo, '', 0,'L', false );
$pdf->Cell(15,6,'INICIO', '', 0,'L', false );
$pdf->Cell(40,6,$generales->inicio, '', 0,'L', false );
$pdf->Cell(15,6,'CURSO', '', 0,'L', false );
$pdf->Cell(1,6,$generales->curso, '', 0,'L', false );
$pdf->SetFont('Times','B',9);
$pdf->Ln(7);
$pdf->Cell(27,6,'TRATAMIENTO ANTERIOR', '', 0,'L', false );
$pdf->SetFont('Times','',9);
$pdf->Ln(5);
$pdf->MultiCell(160, 5,$generales->tratamiento_anterior, '', 'L', false);
$pdf->SetFont('Times','',9);
$pdf->Ln(3);
$pdf->Cell(27,6,'SINTOMAS', '', 0,'L', false );
$pdf->Cell(27,6,$generales->sintomas, '', 0,'L', false );
$pdf->SetFont('Times','',9);
$pdf->Ln(6);
$pdf->Cell(40,6,'SIGNOS VITALES ', '', 0,'L', false );
$pdf->Cell(10,6,'P/A:', '', 0,'L', false );
$pdf->Cell(10,6,$generales->presion_arterial, '', 0,'L', false );
$pdf->Cell(10,6,'FR:', '', 0,'L', false);
$pdf->Cell(10,6,$generales->frecuencia_respiratoria, '', 0,'L', false);
$pdf->Cell(5,6,utf8_decode('T°:'), '', 0,'L', false);
$pdf->Cell(10,6,$generales->temperatura, '', 0,'L', false);
$pdf->Cell(10,6,'SPO2:', '', 0,'L', false);
$pdf->Cell(15,6,$generales->saturacion, '', 0,'L', false);
$pdf->Cell(22,6,'TALLA:', '', 0,'L', false);
$pdf->Cell(1,6,$generales->talla, '', 0,'L', false);
$pdf->Ln(6);
$pdf->Cell(40,6,'FUNCIONES BIOLOGICAS', '', 0,'L', false );
$pdf->Cell(20,6,'APETITO:', '', 0,'L', false );
$pdf->Cell(25,6,$generales->apetito, '', 0,'L', false );
$pdf->Cell(10,6,'SED:', '', 0,'L', false);
$pdf->Cell(25,6,$generales->sed, '', 0,'L', false);
$pdf->Cell(15,6,'ORINA:', '', 0,'L', false);
$pdf->Cell(5,6,$generales->orina, '', 0,'L', false);
$pdf->SetFont('Times','',9);
$pdf->Ln(7);
$pdf->Cell(27,6,'3. EXAMEN FISICO:', '', 0,'L', false );
$pdf->Ln(7);
$pdf->Cell(20,6,'A. CABEZA:', '', 0,'L', false );
$pdf->Cell(60,6,$generales->cabeza, '', 0,'L', false );
$pdf->Cell(20,6,'B. CUELLO:', '', 0,'L', false );
$pdf->Cell(40,6,$generales->cuello, '', 0,'L', false );
$pdf->Ln(7);
$pdf->Cell(35,6,'C. APRESPIRATORIA:', '', 0,'L', false );
$pdf->Cell(45,6,$generales->ap_respiratoria, '', 0,'L', false );
$pdf->Cell(45,6,'D. APCARDIOVASCULAR:', '', 0,'L', false );
$pdf->Cell(20,6,$generales->ap_cardio, '', 0,'L', false );
$pdf->Ln(7);
$pdf->Cell(35,6,'E . ABDOMEN:', '', 0,'L', false );
$pdf->Cell(45,6,$generales->abdomen, '', 0,'L', false );
$pdf->Cell(45,6,'F . AP. GENITOURINARIO:', '', 0,'L', false );
$pdf->Cell(20,6,$generales->ap_genitourinario, '', 0,'L', false );
$pdf->Ln(7);
$pdf->Cell(35,6,'G . LOCOMOTOR:', '', 0,'L', false );
$pdf->Cell(45,6,$generales->loco_motor, '', 0,'L', false );
$pdf->Cell(45,6,'H . SISTEMA NERVIOSO:', '', 0,'L', false );
$pdf->Cell(20,6,$generales->sistema_nervioso, '', 0,'L', false );
$pdf->SetFont('Times','B',9);
$pdf->Ln(7);
$pdf->Cell(27,6,'4. DIAGNOSTICO:', '', 0,'L', false );
$pdf->SetFont('Times','',9);
$pdf->Ln(5);
foreach($diagnostico->result() as $diagnosticos){
$pdf->MultiCell(160, 5,$diagnosticos->clave." - ".$diagnosticos->descripcion, '', 'L', false);
}
$pdf->SetFont('Times','B',9);
$pdf->Ln(5);
$pdf->Cell(27,6,'5. PLAN DE TRABAJO:', '', 0,'L', false );
$pdf->SetFont('Times','',9);
$pdf->Ln(5);
$pdf->MultiCell(160, 5,$generales->plan_trabajo, '', 'L', false);
$pdf->Ln(5);
$pdf->Cell(45,6,'EXAMEN DE AYUDA AL DX:', '', 0,'L', false );
$pdf->Cell(45,6,$generales->examen_dx, '', 0,'L', false );
$pdf->Ln(5);
$pdf->Cell(45,6,'PROCEDIMIENTOS:', '', 0,'L', false );
$pdf->Cell(45,6,$generales->procedimientos, '', 0,'L', false );
$pdf->Ln(5);
$pdf->Cell(45,6,'INTERCONSULTAS:', '', 0,'L', false );
$pdf->Cell(45,6,$generales->interconsultas, '', 0,'L', false );
$pdf->SetFont('Times','B',9);
$pdf->Ln(7);
$pdf->Cell(27,6,'6. TRATAMIENTO:', '', 0,'L', false );
$pdf->SetFont('Times','',9);
$pdf->Ln(5);
$pdf->MultiCell(160, 5,$generales->tratamiento, '', 'L', false);
$pdf->Ln(8);
$pdf->Cell(40,6,'PROXIMA CITA', '', 0,'L', false );
$pdf->Cell(90,6,$generales->proxima_cita, '', 0,'L', false );
$pdf->Cell(115,6,'FIRMA DEL MEDICO', '', 0,'L', false );
$pdf->Ln(5);
$pdf->Cell(40,6,'', '', 0,'L', false );
$pdf->Cell(90,6,'', '', 0,'L', false );
$pdf->Cell(115,6,'_____________________________', '', 0,'L', false );
$pdf->Output();

?>